---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: vera-traefik
      labels:
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.11.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: vera
      annotations:
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: vera
      ports:
      - port: 80
        name: web
        targetPort: "web"
        protocol: "TCP"
      - port: 443
        name: websecure
        targetPort: "websecure"
        protocol: "TCP"
