apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: ebs-plugin
        args:
        # - {all,controller,node} # specify the driver mode
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --v=5
        - --extra-tags=cluster=CLUSTER_NAME # {"$kpt-set":"cluster-name"}
