apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../upstream
images:
- name: k8s.gcr.io/autoscaling/cluster-autoscaler
  newName: k8s.gcr.io/autoscaling/cluster-autoscaler
  newTag: v1.18.3 # {"$kpt-set":"autoscaler-image-tag"}
patches:
- path: patches/cluster-autoscaler-patch.yaml
