apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- traefik/templates/rbac/serviceaccount.yaml
- traefik/templates/rbac/clusterrole.yaml
- traefik/templates/rbac/clusterrolebinding.yaml
- traefik/templates/deployment.yaml
- traefik/templates/service.yaml
- traefik/templates/dashboard-hook-ingressroute.yaml
namespace: traefik-v2
