---
# Source: traefik/templates/rbac/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vera-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: vera
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vera-traefik
subjects:
  - kind: ServiceAccount
    name: vera-traefik
    namespace: traefik-v2
